spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/local
        git:
          uri: https://github.com/rohithpeddi3/microservice_exploration/tree/dockerize/mse-config-server
  profiles:
    active: native

server:
  port: 8888

security:
  user:
    password: ${CONFIG_SERVICE_PASSWORD}