# ===================================================================
# Spring Boot configuration to run locally.
# ===================================================================

spring:
  datasource:
    url: jdbc:mysql://db:3306/mse_product?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      data-source-class-name: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      minimum-idle: 3
      max-lifetime: 2000000
      connection-timeout: 30000
      idle-timeout: 30000
      connection-test-query: SELECT 1
      pool-name: SpringBootHikariCP
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 250
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8120
  context-path: /

eureka:
  instance:
    hostname: mse-product
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://mse-service-registry:9150/eureka}

